-- ============================================================
-- XIN-AI 数据库表与字段备注 (PostgreSQL COMMENT ON)
-- 数据库: XIN (共 47 张表, 516 个字段备注, 563 条 COMMENT 语句)
-- 包含:
--   pro-cowork 28 表: pro_projects/pro_modules/pro_phases/pro_progress_tasks/pro_meetings/
--                     pro_meeting_items/pro_weekly_reports/pro_weekly_kpis/pro_weekly_progress_items/
--                     pro_weekly_plan_tasks/pro_weekly_risks/pro_weekly_work_tasks/pro_project_members/
--                     pro_personal_reports/pro_personal_report_work_items/pro_personal_report_plan_items/
--                     agents/agent_sessions/agent_messages/agent_memories/skills/skill_executions/
--                     task_runs/task_run_events/sys_user_credentials/sys_login_logs/sys_operation_logs/
--                     sys_files (MinIO 文件登记, 各应用共享)
--   rag-cowork 13 表: rag_knowledge_bases/rag_kb_permissions/rag_doc_permissions (文档级授权)/
--                     rag_documents/rag_chunks/rag_multimodal_resources/rag_entities/rag_relations/
--                     rag_sync_events/rag_parse_tasks/rag_query_logs/rag_obsidian_configs (Obsidian 对接)/
--                     sys_users (三系统共享)
--   mcp-cowork 6 表:  mcp_servers/mcp_tools/mcp_test_cases/mcp_call_logs/
--                     mcp_im_channels (个人IM通道)/mcp_inspect_reports (工具巡检报告)
--
-- 执行方式 (推荐, 通过 pg_db 容器):
--   docker exec -i pg_db psql -U dbuser -d XIN < scripts/db_comments.sql
--
-- 或宿主机直连:
--   psql -h localhost -p 11000 -U dbuser -d XIN -f scripts/db_comments.sql
--
-- 特点: COMMENT 语句幂等, 可重复执行, 仅更新备注不改表结构
-- 说明: 本文件由各项目 ORM 模型 (app/models/*.py 中的 comment=) 自动汇总生成,
--       修改注释请同步修改对应 ORM 模型后重新生成本文件
-- ============================================================


-- ===============================================================
-- pro-cowork 表 (项目管理智能体工作平台, 含 MinIO 文件登记 sys_files)
-- ===============================================================

COMMENT ON TABLE agents IS '智能体定义表';
COMMENT ON COLUMN agents.id IS '主键ID';
COMMENT ON COLUMN agents.name IS '智能体名称';
COMMENT ON COLUMN agents.type IS '类型: progress进度/meeting会议/weekly_report周报/work_plan工作计划/custom自定义';
COMMENT ON COLUMN agents.description IS '智能体描述';
COMMENT ON COLUMN agents.system_prompt IS '系统提示词';
COMMENT ON COLUMN agents.config IS '配置参数 (JSON)';
COMMENT ON COLUMN agents.tools IS '可用工具列表 (JSON)';
COMMENT ON COLUMN agents.is_active IS '是否启用';
COMMENT ON COLUMN agents.created_at IS '创建时间';
COMMENT ON COLUMN agents.updated_at IS '更新时间';
COMMENT ON COLUMN agents.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_projects IS '项目元信息表 (一个项目对应一张进度计划执行图)';
COMMENT ON COLUMN pro_projects.id IS '主键ID';
COMMENT ON COLUMN pro_projects.name IS '项目名, 如 "信投AI2.0"';
COMMENT ON COLUMN pro_projects.title IS '执行图标题';
COMMENT ON COLUMN pro_projects.based_doc IS '基于文档';
COMMENT ON COLUMN pro_projects.manager IS '项目经理';
COMMENT ON COLUMN pro_projects.status IS '项目状态: 进行中/已停止/已完成';
COMMENT ON COLUMN pro_projects.start_date IS '项目开始日期';
COMMENT ON COLUMN pro_projects.end_date IS '项目结束日期';
COMMENT ON COLUMN pro_projects.is_active IS '是否当前项目';
COMMENT ON COLUMN pro_projects.sort_order IS '排序序号';
COMMENT ON COLUMN pro_projects.created_at IS '创建时间';
COMMENT ON COLUMN pro_projects.updated_at IS '更新时间';
COMMENT ON COLUMN pro_projects.is_delete IS '是否已软删除';
COMMENT ON TABLE skills IS '技能定义表';
COMMENT ON COLUMN skills.id IS '主键ID';
COMMENT ON COLUMN skills.name IS '技能名称';
COMMENT ON COLUMN skills.description IS '技能描述';
COMMENT ON COLUMN skills.category IS '分类: data数据/api接口/workflow工作流/notification通知';
COMMENT ON COLUMN skills.trigger_type IS '触发方式: manual手动/scheduled定时/event事件';
COMMENT ON COLUMN skills.config IS '配置参数 (JSON)';
COMMENT ON COLUMN skills.code IS '技能执行代码';
COMMENT ON COLUMN skills.is_active IS '是否启用';
COMMENT ON COLUMN skills.created_at IS '创建时间';
COMMENT ON COLUMN skills.updated_at IS '更新时间';
COMMENT ON COLUMN skills.is_delete IS '是否已软删除';
COMMENT ON TABLE sys_files IS 'MinIO 文件登记表 (各应用上传对象统一登记, bucket+object_key 唯一)';
COMMENT ON COLUMN sys_files.id IS '主键ID';
COMMENT ON COLUMN sys_files.file_name IS '文件名';
COMMENT ON COLUMN sys_files.file_type IS '文件类型 (扩展名小写, 如 pdf/png/m4a)';
COMMENT ON COLUMN sys_files.file_size IS '文件大小(字节)';
COMMENT ON COLUMN sys_files.app IS '上传应用: pro-cowork/rag-cowork';
COMMENT ON COLUMN sys_files.object_name IS '关联对象 (智能体名称/技能名称/知识库名称等)';
COMMENT ON COLUMN sys_files.member_name IS '上传人姓名';
COMMENT ON COLUMN sys_files.bucket IS 'MinIO 存储桶';
COMMENT ON COLUMN sys_files.object_key IS 'MinIO 存储路径 (桶内对象 key)';
COMMENT ON COLUMN sys_files.content_type IS 'MIME 类型';
COMMENT ON COLUMN sys_files.kb_indexed IS '是否已构建到知识库 (rag 解析入库成功后回写)';
COMMENT ON COLUMN sys_files.uploaded_at IS '文件上传时间 (MinIO 对象最后修改时间)';
COMMENT ON COLUMN sys_files.created_at IS '创建时间';
COMMENT ON COLUMN sys_files.updated_at IS '更新时间';
COMMENT ON COLUMN sys_files.is_delete IS '是否已软删除';
COMMENT ON TABLE sys_login_logs IS '登录日志表 (每次身份确认均记录, 含无效姓名)';
COMMENT ON COLUMN sys_login_logs.id IS '主键ID';
COMMENT ON COLUMN sys_login_logs.user_name IS '登录姓名';
COMMENT ON COLUMN sys_login_logs.is_valid IS '是否为有效项目成员';
COMMENT ON COLUMN sys_login_logs.ip IS '客户端IP';
COMMENT ON COLUMN sys_login_logs.user_agent IS '浏览器 User-Agent';
COMMENT ON COLUMN sys_login_logs.created_at IS '创建时间';
COMMENT ON COLUMN sys_login_logs.updated_at IS '更新时间';
COMMENT ON COLUMN sys_login_logs.is_delete IS '是否已软删除';
COMMENT ON TABLE sys_operation_logs IS '操作日志表 (中间件自动记录全部写操作 + LLM 调用 token)';
COMMENT ON COLUMN sys_operation_logs.id IS '主键ID';
COMMENT ON COLUMN sys_operation_logs.user_name IS '操作人姓名';
COMMENT ON COLUMN sys_operation_logs.method IS 'HTTP 方法 / LLM';
COMMENT ON COLUMN sys_operation_logs.path IS '请求路径 / 调用来源';
COMMENT ON COLUMN sys_operation_logs.entity_type IS '实体类型 (会议/项目周报/...)';
COMMENT ON COLUMN sys_operation_logs.entity_id IS '实体ID (可空)';
COMMENT ON COLUMN sys_operation_logs.action IS '操作类型: create/update/delete/llm_call/export';
COMMENT ON COLUMN sys_operation_logs.detail IS '补充说明';
COMMENT ON COLUMN sys_operation_logs.tokens IS 'LLM token 消耗';
COMMENT ON COLUMN sys_operation_logs.created_at IS '创建时间';
COMMENT ON COLUMN sys_operation_logs.updated_at IS '更新时间';
COMMENT ON COLUMN sys_operation_logs.is_delete IS '是否已软删除';
COMMENT ON TABLE sys_user_credentials IS '成员登录凭据表 (姓名唯一, 同人跨项目共用同一密码)';
COMMENT ON COLUMN sys_user_credentials.id IS '主键ID';
COMMENT ON COLUMN sys_user_credentials.name IS '成员姓名 (唯一)';
COMMENT ON COLUMN sys_user_credentials.password_hash IS '密码哈希 (格式: salt$pbkdf2 hex, 空表示未设置密码)';
COMMENT ON COLUMN sys_user_credentials.created_at IS '创建时间';
COMMENT ON COLUMN sys_user_credentials.updated_at IS '更新时间';
COMMENT ON COLUMN sys_user_credentials.is_delete IS '是否已软删除';
COMMENT ON TABLE agent_sessions IS '智能体会话表';
COMMENT ON COLUMN agent_sessions.id IS '主键ID';
COMMENT ON COLUMN agent_sessions.agent_id IS '所属智能体ID (FK→agents.id)';
COMMENT ON COLUMN agent_sessions.title IS '会话标题';
COMMENT ON COLUMN agent_sessions.status IS '状态: active活跃/archived已归档';
COMMENT ON COLUMN agent_sessions.created_at IS '创建时间';
COMMENT ON COLUMN agent_sessions.updated_at IS '更新时间';
COMMENT ON COLUMN agent_sessions.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_meetings IS '项目会议表 (会议主记录, 含录音转写)';
COMMENT ON COLUMN pro_meetings.id IS '主键ID';
COMMENT ON COLUMN pro_meetings.project_id IS '所属项目ID (FK→pro_projects.id)';
COMMENT ON COLUMN pro_meetings.title IS '会议主题';
COMMENT ON COLUMN pro_meetings.meet_date IS '会议日期, 如 ''2026-07-21''';
COMMENT ON COLUMN pro_meetings.meet_time IS '会议时间, 如 ''09:00-10:00''';
COMMENT ON COLUMN pro_meetings.place IS '会议地点';
COMMENT ON COLUMN pro_meetings.host IS '主持人';
COMMENT ON COLUMN pro_meetings.attendees IS '参会人员 (逗号分隔)';
COMMENT ON COLUMN pro_meetings.description IS '会议描述/纪要';
COMMENT ON COLUMN pro_meetings.audio_file IS '原始录音文件名 (任务附件目录内)';
COMMENT ON COLUMN pro_meetings.transcript IS '录音转写完整文字 (带时间戳)';
COMMENT ON COLUMN pro_meetings.sort_order IS '排序序号';
COMMENT ON COLUMN pro_meetings.created_at IS '创建时间';
COMMENT ON COLUMN pro_meetings.updated_at IS '更新时间';
COMMENT ON COLUMN pro_meetings.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_modules IS '项目模块字典表 (底座/数据/智能体/应用/需求/协调, 按项目隔离)';
COMMENT ON COLUMN pro_modules.id IS '主键ID';
COMMENT ON COLUMN pro_modules.project_id IS '所属项目ID (FK→pro_projects.id)';
COMMENT ON COLUMN pro_modules.idx IS '模块编号, 如 ''01'',''02''...';
COMMENT ON COLUMN pro_modules.tag IS '模块标签: 底座/数据/智能体/应用/需求/协调';
COMMENT ON COLUMN pro_modules.title IS '模块标题';
COMMENT ON COLUMN pro_modules.owner IS '负责人';
COMMENT ON COLUMN pro_modules.color IS '主题色';
COMMENT ON COLUMN pro_modules.color_bg IS '背景色';
COMMENT ON COLUMN pro_modules.sort_order IS '排序序号';
COMMENT ON COLUMN pro_modules.created_at IS '创建时间';
COMMENT ON COLUMN pro_modules.updated_at IS '更新时间';
COMMENT ON COLUMN pro_modules.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_personal_reports IS '个人周报主表 (每人每周一份, 按项目上下文隔离)';
COMMENT ON COLUMN pro_personal_reports.id IS '主键ID';
COMMENT ON COLUMN pro_personal_reports.project_id IS '所属项目ID (FK→pro_projects.id, 填报上下文)';
COMMENT ON COLUMN pro_personal_reports.member_name IS '填报人姓名 (来自项目成员)';
COMMENT ON COLUMN pro_personal_reports.week_start IS '周报周期起 (周一)';
COMMENT ON COLUMN pro_personal_reports.week_end IS '周报周期止 (周日)';
COMMENT ON COLUMN pro_personal_reports.summary IS '周报概括 (AI 生成 2-3 段: 本周主要工作内容 + 下周工作计划, 支持人工修改)';
COMMENT ON COLUMN pro_personal_reports.created_at IS '创建时间';
COMMENT ON COLUMN pro_personal_reports.updated_at IS '更新时间';
COMMENT ON COLUMN pro_personal_reports.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_phases IS '项目阶段字典表 (第一阶段/第二阶段/第三阶段, 按项目隔离)';
COMMENT ON COLUMN pro_phases.id IS '主键ID';
COMMENT ON COLUMN pro_phases.project_id IS '所属项目ID (FK→pro_projects.id)';
COMMENT ON COLUMN pro_phases.name IS '阶段名称: 第一阶段/第二阶段/第三阶段';
COMMENT ON COLUMN pro_phases.subtitle IS '阶段副标题: 有得用/用起来/用得好';
COMMENT ON COLUMN pro_phases.description IS '阶段描述';
COMMENT ON COLUMN pro_phases.start_date IS '阶段开始日期';
COMMENT ON COLUMN pro_phases.end_date IS '阶段结束日期';
COMMENT ON COLUMN pro_phases.created_at IS '创建时间';
COMMENT ON COLUMN pro_phases.updated_at IS '更新时间';
COMMENT ON COLUMN pro_phases.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_project_members IS '项目成员表 (维护所选项目的成员: 角色/岗位、入组时间、当前状态)';
COMMENT ON COLUMN pro_project_members.id IS '主键ID';
COMMENT ON COLUMN pro_project_members.project_id IS '所属项目ID (FK→pro_projects.id)';
COMMENT ON COLUMN pro_project_members.name IS '成员姓名';
COMMENT ON COLUMN pro_project_members.role IS '角色/岗位';
COMMENT ON COLUMN pro_project_members.join_date IS '入组时间';
COMMENT ON COLUMN pro_project_members.status IS '当前状态: 全职/临时/退出';
COMMENT ON COLUMN pro_project_members.sort_order IS '排序序号';
COMMENT ON COLUMN pro_project_members.created_at IS '创建时间';
COMMENT ON COLUMN pro_project_members.updated_at IS '更新时间';
COMMENT ON COLUMN pro_project_members.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_weekly_reports IS '项目周报表';
COMMENT ON COLUMN pro_weekly_reports.id IS '主键ID';
COMMENT ON COLUMN pro_weekly_reports.project_id IS '所属项目ID (FK→pro_projects.id)';
COMMENT ON COLUMN pro_weekly_reports.title IS '周报标题';
COMMENT ON COLUMN pro_weekly_reports.week_range IS '周报周期展示文本, 如 ''07.01 — 07.07''';
COMMENT ON COLUMN pro_weekly_reports.week_start IS '周报周期开始日期';
COMMENT ON COLUMN pro_weekly_reports.week_end IS '周报周期结束日期';
COMMENT ON COLUMN pro_weekly_reports.overview_summary IS '本周概览总结';
COMMENT ON COLUMN pro_weekly_reports.week_digest IS '周报概括 (AI 生成, 微信汇报版)';
COMMENT ON COLUMN pro_weekly_reports.status IS '状态: draft草稿/submitted已提交';
COMMENT ON COLUMN pro_weekly_reports.created_at IS '创建时间';
COMMENT ON COLUMN pro_weekly_reports.updated_at IS '更新时间';
COMMENT ON COLUMN pro_weekly_reports.is_delete IS '是否已软删除';
COMMENT ON TABLE agent_memories IS '智能体记忆表';
COMMENT ON COLUMN agent_memories.id IS '主键ID';
COMMENT ON COLUMN agent_memories.agent_id IS '所属智能体ID (FK→agents.id)';
COMMENT ON COLUMN agent_memories.project_id IS '关联项目ID (FK→pro_projects.id, 可空)';
COMMENT ON COLUMN agent_memories.session_id IS '来源会话ID (FK→agent_sessions.id, 可空)';
COMMENT ON COLUMN agent_memories.memory_type IS '记忆类型: fact事实/preference偏好/context上下文/decision决策';
COMMENT ON COLUMN agent_memories.key IS '记忆键名';
COMMENT ON COLUMN agent_memories.content IS '记忆内容';
COMMENT ON COLUMN agent_memories.extra_data IS '扩展数据 (JSON)';
COMMENT ON COLUMN agent_memories.created_at IS '创建时间';
COMMENT ON COLUMN agent_memories.is_delete IS '是否已软删除';
COMMENT ON TABLE agent_messages IS '智能体会话消息表';
COMMENT ON COLUMN agent_messages.id IS '主键ID';
COMMENT ON COLUMN agent_messages.session_id IS '所属会话ID (FK→agent_sessions.id)';
COMMENT ON COLUMN agent_messages.role IS '角色: user用户/assistant助手/system系统/tool工具';
COMMENT ON COLUMN agent_messages.content IS '消息内容';
COMMENT ON COLUMN agent_messages.tool_calls IS '工具调用请求 (JSON, 可空)';
COMMENT ON COLUMN agent_messages.tool_results IS '工具调用结果 (JSON, 可空)';
COMMENT ON COLUMN agent_messages.tokens_used IS '消耗的 token 数';
COMMENT ON COLUMN agent_messages.created_at IS '创建时间';
COMMENT ON COLUMN agent_messages.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_meeting_items IS '会议议程项表';
COMMENT ON COLUMN pro_meeting_items.id IS '主键ID';
COMMENT ON COLUMN pro_meeting_items.meeting_id IS '所属会议ID (FK→pro_meetings.id)';
COMMENT ON COLUMN pro_meeting_items.item_time IS '时间段, 如 ''09:00-09:10''';
COMMENT ON COLUMN pro_meeting_items.theme IS '议程主题';
COMMENT ON COLUMN pro_meeting_items.speaker IS '汇报人';
COMMENT ON COLUMN pro_meeting_items.duration IS '时长, 如 ''10分钟''';
COMMENT ON COLUMN pro_meeting_items.note IS '备注';
COMMENT ON COLUMN pro_meeting_items.description IS '议程内容简介';
COMMENT ON COLUMN pro_meeting_items.sort_order IS '排序序号';
COMMENT ON COLUMN pro_meeting_items.created_at IS '创建时间';
COMMENT ON COLUMN pro_meeting_items.updated_at IS '更新时间';
COMMENT ON COLUMN pro_meeting_items.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_personal_report_plan_items IS '个人周报下周工作计划表 (动态行: 项目 + 计划内容)';
COMMENT ON COLUMN pro_personal_report_plan_items.id IS '主键ID';
COMMENT ON COLUMN pro_personal_report_plan_items.report_id IS '所属个人周报ID (FK→pro_personal_reports.id)';
COMMENT ON COLUMN pro_personal_report_plan_items.project_id IS '计划所属项目ID (FK→pro_projects.id, 可空)';
COMMENT ON COLUMN pro_personal_report_plan_items.content IS '计划内容';
COMMENT ON COLUMN pro_personal_report_plan_items.sort_order IS '排序序号';
COMMENT ON COLUMN pro_personal_report_plan_items.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_personal_report_work_items IS '个人周报本周工作内容表 (动态行: 每行一天)';
COMMENT ON COLUMN pro_personal_report_work_items.id IS '主键ID';
COMMENT ON COLUMN pro_personal_report_work_items.report_id IS '所属个人周报ID (FK→pro_personal_reports.id)';
COMMENT ON COLUMN pro_personal_report_work_items.project_id IS '工作内容所属项目ID (FK→pro_projects.id, 可空)';
COMMENT ON COLUMN pro_personal_report_work_items.day_of_week IS '周几: 1=周一 ~ 7=周日';
COMMENT ON COLUMN pro_personal_report_work_items.content IS '当天工作内容';
COMMENT ON COLUMN pro_personal_report_work_items.participants IS '参与人员';
COMMENT ON COLUMN pro_personal_report_work_items.deliverable IS '交付物';
COMMENT ON COLUMN pro_personal_report_work_items.hours IS '工时(H)';
COMMENT ON COLUMN pro_personal_report_work_items.sort_order IS '排序序号';
COMMENT ON COLUMN pro_personal_report_work_items.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_progress_tasks IS '项目进度计划任务表';
COMMENT ON COLUMN pro_progress_tasks.id IS '主键ID';
COMMENT ON COLUMN pro_progress_tasks.project_id IS '所属项目ID (FK→pro_projects.id)';
COMMENT ON COLUMN pro_progress_tasks.task_uid IS '任务唯一编号, 如 ''1-1'',''M1''';
COMMENT ON COLUMN pro_progress_tasks.name IS '任务名称';
COMMENT ON COLUMN pro_progress_tasks.phase_id IS '所属阶段ID (FK→pro_phases.id, 可空)';
COMMENT ON COLUMN pro_progress_tasks.start_date IS '开始日期';
COMMENT ON COLUMN pro_progress_tasks.end_date IS '结束日期';
COMMENT ON COLUMN pro_progress_tasks.status IS '状态: ongoing进行中/planned待启动/milestone里程碑/done已完成/deleted已删除';
COMMENT ON COLUMN pro_progress_tasks.full_desc IS '完整描述(含责任方)';
COMMENT ON COLUMN pro_progress_tasks.owner IS '责任人';
COMMENT ON COLUMN pro_progress_tasks.is_milestone IS '是否里程碑';
COMMENT ON COLUMN pro_progress_tasks.created_at IS '创建时间';
COMMENT ON COLUMN pro_progress_tasks.updated_at IS '更新时间';
COMMENT ON COLUMN pro_progress_tasks.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_weekly_kpis IS '周报KPI表 (本周概览, 每模块一条)';
COMMENT ON COLUMN pro_weekly_kpis.id IS '主键ID';
COMMENT ON COLUMN pro_weekly_kpis.report_id IS '所属周报ID (FK→pro_weekly_reports.id)';
COMMENT ON COLUMN pro_weekly_kpis.module_id IS '所属模块ID (FK→pro_modules.id)';
COMMENT ON COLUMN pro_weekly_kpis.progress_pct IS '完成进度百分比 (0-100)';
COMMENT ON COLUMN pro_weekly_kpis.status IS '健康状态: 正常/关注/风险';
COMMENT ON COLUMN pro_weekly_kpis.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_weekly_progress_items IS '周报本周进展表 (每模块多条)';
COMMENT ON COLUMN pro_weekly_progress_items.id IS '主键ID';
COMMENT ON COLUMN pro_weekly_progress_items.report_id IS '所属周报ID (FK→pro_weekly_reports.id)';
COMMENT ON COLUMN pro_weekly_progress_items.module_id IS '所属模块ID (FK→pro_modules.id)';
COMMENT ON COLUMN pro_weekly_progress_items.content IS '事项标题';
COMMENT ON COLUMN pro_weekly_progress_items.detail IS '补充说明';
COMMENT ON COLUMN pro_weekly_progress_items.sort_order IS '排序序号';
COMMENT ON COLUMN pro_weekly_progress_items.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_weekly_risks IS '周报风险与应对表';
COMMENT ON COLUMN pro_weekly_risks.id IS '主键ID';
COMMENT ON COLUMN pro_weekly_risks.report_id IS '所属周报ID (FK→pro_weekly_reports.id)';
COMMENT ON COLUMN pro_weekly_risks.seq IS '风险编号, 如 ''R1'',''R2''';
COMMENT ON COLUMN pro_weekly_risks.title IS '风险标题';
COMMENT ON COLUMN pro_weekly_risks.coordination IS '需要协调的内容';
COMMENT ON COLUMN pro_weekly_risks.urgency IS '紧急程度: 高/中/低';
COMMENT ON COLUMN pro_weekly_risks.sort_order IS '排序序号';
COMMENT ON COLUMN pro_weekly_risks.is_delete IS '是否已软删除';
COMMENT ON TABLE skill_executions IS '技能执行记录表';
COMMENT ON COLUMN skill_executions.id IS '主键ID';
COMMENT ON COLUMN skill_executions.skill_id IS '所属技能ID (FK→skills.id)';
COMMENT ON COLUMN skill_executions.session_id IS '来源会话ID (FK→agent_sessions.id, 可空)';
COMMENT ON COLUMN skill_executions.input_data IS '输入数据 (JSON)';
COMMENT ON COLUMN skill_executions.output_data IS '输出数据 (JSON)';
COMMENT ON COLUMN skill_executions.status IS '状态: pending待执行/running执行中/success成功/failed失败';
COMMENT ON COLUMN skill_executions.error IS '错误信息';
COMMENT ON COLUMN skill_executions.duration_ms IS '执行耗时(毫秒)';
COMMENT ON COLUMN skill_executions.created_at IS '创建时间';
COMMENT ON COLUMN skill_executions.is_delete IS '是否已软删除';
COMMENT ON TABLE task_runs IS '工作台任务表 (选择项目/文件/智能体/技能后的一次执行记录)';
COMMENT ON COLUMN task_runs.id IS '主键ID';
COMMENT ON COLUMN task_runs.project_id IS '所属项目ID (FK→pro_projects.id, 可空)';
COMMENT ON COLUMN task_runs.agent_id IS '执行智能体ID (FK→agents.id, 可空: 创建时不指定, 由意图识别/用户选择确定)';
COMMENT ON COLUMN task_runs.title IS '任务标题';
COMMENT ON COLUMN task_runs.input_text IS '用户输入文本';
COMMENT ON COLUMN task_runs.skill_ids IS '选用的技能ID列表 (JSON)';
COMMENT ON COLUMN task_runs.file_names IS '附件文件名列表 (JSON)';
COMMENT ON COLUMN task_runs.status IS '状态: draft草稿/running执行中/done已完成/failed失败';
COMMENT ON COLUMN task_runs.user_name IS '创建人姓名 (首页看板按人过滤)';
COMMENT ON COLUMN task_runs.result_text IS '执行结果文本';
COMMENT ON COLUMN task_runs.session_id IS '关联会话ID (FK→agent_sessions.id, 可空)';
COMMENT ON COLUMN task_runs.created_at IS '创建时间';
COMMENT ON COLUMN task_runs.updated_at IS '更新时间';
COMMENT ON COLUMN task_runs.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_weekly_plan_tasks IS '周报下周任务表 (核心关联表, 可关联进度计划任务)';
COMMENT ON COLUMN pro_weekly_plan_tasks.id IS '主键ID';
COMMENT ON COLUMN pro_weekly_plan_tasks.report_id IS '所属周报ID (FK→pro_weekly_reports.id)';
COMMENT ON COLUMN pro_weekly_plan_tasks.module_id IS '所属模块ID (FK→pro_modules.id)';
COMMENT ON COLUMN pro_weekly_plan_tasks.progress_task_id IS '关联进度计划任务ID (FK→pro_progress_tasks.id, 可空)';
COMMENT ON COLUMN pro_weekly_plan_tasks.name IS '任务/事项名称';
COMMENT ON COLUMN pro_weekly_plan_tasks.is_key IS '是否重点任务';
COMMENT ON COLUMN pro_weekly_plan_tasks.owner IS '责任人';
COMMENT ON COLUMN pro_weekly_plan_tasks.plan_period IS '计划周期';
COMMENT ON COLUMN pro_weekly_plan_tasks.status IS '状态: 待开始/进行中/已完成';
COMMENT ON COLUMN pro_weekly_plan_tasks.remark IS '备注';
COMMENT ON COLUMN pro_weekly_plan_tasks.sort_order IS '排序序号';
COMMENT ON COLUMN pro_weekly_plan_tasks.created_at IS '创建时间';
COMMENT ON COLUMN pro_weekly_plan_tasks.updated_at IS '更新时间';
COMMENT ON COLUMN pro_weekly_plan_tasks.is_delete IS '是否已软删除';
COMMENT ON TABLE task_run_events IS '任务执行事件表 (过程回放/断线续看)';
COMMENT ON COLUMN task_run_events.id IS '主键ID';
COMMENT ON COLUMN task_run_events.run_id IS '所属任务ID (FK→task_runs.id)';
COMMENT ON COLUMN task_run_events.seq IS '事件序号 (任务内单调递增)';
COMMENT ON COLUMN task_run_events.type IS '事件类型: user/content/tool_call/tool_result/error/done/intent/choice_request/choice_done/model/asr_segment/asr_done/minutes_delta';
COMMENT ON COLUMN task_run_events.name IS '工具名 (tool_* 事件)';
COMMENT ON COLUMN task_run_events.payload IS '事件载荷 (JSON)';
COMMENT ON COLUMN task_run_events.created_at IS '创建时间';
COMMENT ON COLUMN task_run_events.updated_at IS '更新时间';
COMMENT ON COLUMN task_run_events.is_delete IS '是否已软删除';
COMMENT ON TABLE pro_weekly_work_tasks IS '每周工作任务安排表 (核心关联表, 可关联周报下周任务)';
COMMENT ON COLUMN pro_weekly_work_tasks.id IS '主键ID';
COMMENT ON COLUMN pro_weekly_work_tasks.project_id IS '所属项目ID (FK→pro_projects.id)';
COMMENT ON COLUMN pro_weekly_work_tasks.week_start IS '周开始日期';
COMMENT ON COLUMN pro_weekly_work_tasks.week_end IS '周结束日期';
COMMENT ON COLUMN pro_weekly_work_tasks.plan_task_id IS '关联周报下周任务ID (FK→pro_weekly_plan_tasks.id, 可空)';
COMMENT ON COLUMN pro_weekly_work_tasks.name IS '任务名称';
COMMENT ON COLUMN pro_weekly_work_tasks.module_id IS '所属模块ID (FK→pro_modules.id, 可空)';
COMMENT ON COLUMN pro_weekly_work_tasks.owner IS '责任人';
COMMENT ON COLUMN pro_weekly_work_tasks.is_temporary IS '是否临时任务';
COMMENT ON COLUMN pro_weekly_work_tasks.priority IS '优先级: high高/medium中/low低';
COMMENT ON COLUMN pro_weekly_work_tasks.status IS '状态: 待开始/进行中/已完成/已取消';
COMMENT ON COLUMN pro_weekly_work_tasks.planned_hours IS '计划工时(H)';
COMMENT ON COLUMN pro_weekly_work_tasks.actual_hours IS '实际工时(H)';
COMMENT ON COLUMN pro_weekly_work_tasks.remark IS '备注';
COMMENT ON COLUMN pro_weekly_work_tasks.sort_order IS '排序序号';
COMMENT ON COLUMN pro_weekly_work_tasks.created_at IS '创建时间';
COMMENT ON COLUMN pro_weekly_work_tasks.updated_at IS '更新时间';
COMMENT ON COLUMN pro_weekly_work_tasks.is_delete IS '是否已软删除';

-- ===============================================================
-- rag-cowork 表 (知识库平台, 含 Obsidian 对接配置 rag_obsidian_configs 与共享 sys_users)
-- ===============================================================

COMMENT ON TABLE rag_chunks IS '文档分块表: 向量检索与图谱构建的基本单元';
COMMENT ON COLUMN rag_chunks.chunk_id IS '分块ID 主键(雪花ID)';
COMMENT ON COLUMN rag_chunks.doc_id IS '所属文档ID (FK→rag_documents.doc_id)';
COMMENT ON COLUMN rag_chunks.kb_id IS '所属知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_chunks.chunk_index IS '分块序号(文档内顺序)';
COMMENT ON COLUMN rag_chunks.content IS '分块文本内容';
COMMENT ON COLUMN rag_chunks.page_number IS '所在页码';
COMMENT ON COLUMN rag_chunks.chunk_type IS '分块类型: text文本等';
COMMENT ON COLUMN rag_chunks.milvus_id IS 'Milvus向量ID';
COMMENT ON COLUMN rag_chunks.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_chunks.created_at IS '创建时间';
COMMENT ON COLUMN rag_chunks.updated_at IS '更新时间';
COMMENT ON COLUMN rag_chunks.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_documents IS '知识库文档表: 原始文件元信息+MinIO归档+解析状态';
COMMENT ON COLUMN rag_documents.doc_id IS '文档ID 主键(雪花ID)';
COMMENT ON COLUMN rag_documents.kb_id IS '所属知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_documents.file_name IS '文件名称';
COMMENT ON COLUMN rag_documents.file_ext IS '文件扩展名';
COMMENT ON COLUMN rag_documents.file_size IS '文件大小(字节)';
COMMENT ON COLUMN rag_documents.file_hash IS '文件哈希值(用于去重)';
COMMENT ON COLUMN rag_documents.minio_bucket IS 'MinIO存储桶';
COMMENT ON COLUMN rag_documents.minio_path IS 'MinIO对象路径';
COMMENT ON COLUMN rag_documents.parse_status IS '解析状态: pending待解析/parsing解析中/done完成/failed失败';
COMMENT ON COLUMN rag_documents.parser_type IS '解析器类型';
COMMENT ON COLUMN rag_documents.total_chunks IS '分块总数';
COMMENT ON COLUMN rag_documents.total_images IS '图片总数';
COMMENT ON COLUMN rag_documents.total_tables IS '表格总数';
COMMENT ON COLUMN rag_documents.error_msg IS '解析错误信息';
COMMENT ON COLUMN rag_documents.user_id IS '上传者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_documents.created_at IS '创建时间';
COMMENT ON COLUMN rag_documents.updated_at IS '更新时间';
COMMENT ON COLUMN rag_documents.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_entities IS '知识图谱实体表: 命名实体(图谱节点)';
COMMENT ON COLUMN rag_entities.entity_id IS '实体ID 主键(雪花ID)';
COMMENT ON COLUMN rag_entities.kb_id IS '所属知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_entities.doc_id IS '来源文档ID (FK→rag_documents.doc_id)';
COMMENT ON COLUMN rag_entities.entity_name IS '实体名称';
COMMENT ON COLUMN rag_entities.entity_type IS '实体类型(默认UNKNOWN)';
COMMENT ON COLUMN rag_entities.description IS '实体描述';
COMMENT ON COLUMN rag_entities.weight IS '实体权重';
COMMENT ON COLUMN rag_entities.neo4j_node_id IS 'Neo4j节点ID';
COMMENT ON COLUMN rag_entities.milvus_id IS 'Milvus向量ID';
COMMENT ON COLUMN rag_entities.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_entities.created_at IS '创建时间';
COMMENT ON COLUMN rag_entities.updated_at IS '更新时间';
COMMENT ON COLUMN rag_entities.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_kb_permissions IS '知识库权限表: 用户显式授权(read/write/admin)';
COMMENT ON COLUMN rag_kb_permissions.id IS '主键ID(雪花ID)';
COMMENT ON COLUMN rag_kb_permissions.kb_id IS '知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_kb_permissions.user_id IS '被授权用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_kb_permissions.perm IS '权限级别: read只读/write可写/admin管理';
COMMENT ON COLUMN rag_kb_permissions.created_at IS '创建时间';
COMMENT ON COLUMN rag_kb_permissions.updated_at IS '更新时间';
COMMENT ON COLUMN rag_kb_permissions.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_knowledge_bases IS '知识库表: 公司/部门/项目/个人/外接五级知识库';
COMMENT ON COLUMN rag_knowledge_bases.kb_id IS '知识库ID 主键(雪花ID)';
COMMENT ON COLUMN rag_knowledge_bases.name IS '知识库名称';
COMMENT ON COLUMN rag_knowledge_bases.level IS '知识库级别: company公司/department部门/project项目/personal个人/external外接';
COMMENT ON COLUMN rag_knowledge_bases.description IS '知识库描述';
COMMENT ON COLUMN rag_knowledge_bases.owner_user_id IS '所有者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_knowledge_bases.project_id IS '关联项目ID (FK→pro-cowork projects.id, 仅project级)';
COMMENT ON COLUMN rag_knowledge_bases.department IS '所属部门(department级按sys_users.department匹配)';
COMMENT ON COLUMN rag_knowledge_bases.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_knowledge_bases.created_at IS '创建时间';
COMMENT ON COLUMN rag_knowledge_bases.updated_at IS '更新时间';
COMMENT ON COLUMN rag_knowledge_bases.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_multimodal_resources IS '多模态资源表: 文档中的图片/表格/语音, 附AI生成描述参与检索';
COMMENT ON COLUMN rag_multimodal_resources.resource_id IS '资源ID 主键(雪花ID)';
COMMENT ON COLUMN rag_multimodal_resources.doc_id IS '所属文档ID (FK→rag_documents.doc_id)';
COMMENT ON COLUMN rag_multimodal_resources.kb_id IS '所属知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_multimodal_resources.chunk_id IS '关联分块ID (FK→rag_chunks.chunk_id, 可空)';
COMMENT ON COLUMN rag_multimodal_resources.resource_type IS '资源类型: image图片/table表格/audio语音';
COMMENT ON COLUMN rag_multimodal_resources.resource_index IS '资源序号(文档内顺序)';
COMMENT ON COLUMN rag_multimodal_resources.minio_path IS 'MinIO对象路径';
COMMENT ON COLUMN rag_multimodal_resources.content_desc IS 'AI生成的内容描述(参与检索)';
COMMENT ON COLUMN rag_multimodal_resources.milvus_id IS 'Milvus向量ID';
COMMENT ON COLUMN rag_multimodal_resources.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_multimodal_resources.created_at IS '创建时间';
COMMENT ON COLUMN rag_multimodal_resources.updated_at IS '更新时间';
COMMENT ON COLUMN rag_multimodal_resources.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_obsidian_configs IS 'Obsidian连接配置表: 个人知识库对接Obsidian(每人一条)';
COMMENT ON COLUMN rag_obsidian_configs.id IS '主键ID(雪花ID)';
COMMENT ON COLUMN rag_obsidian_configs.user_id IS '所属用户ID (FK→sys_users.user_id, 每人一条)';
COMMENT ON COLUMN rag_obsidian_configs.kb_id IS '同步目标个人知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_obsidian_configs.host IS 'Obsidian Local REST API 地址 (如 https://host.docker.internal:27124)';
COMMENT ON COLUMN rag_obsidian_configs.api_key IS 'Obsidian Local REST API 的 API Key';
COMMENT ON COLUMN rag_obsidian_configs.base_path IS '仅同步该子目录(空=整个vault)';
COMMENT ON COLUMN rag_obsidian_configs.auto_parse IS '同步后是否自动触发解析入库';
COMMENT ON COLUMN rag_obsidian_configs.last_sync_at IS '最近同步时间';
COMMENT ON COLUMN rag_obsidian_configs.last_sync_info IS '最近同步结果摘要';
COMMENT ON COLUMN rag_obsidian_configs.created_at IS '创建时间';
COMMENT ON COLUMN rag_obsidian_configs.updated_at IS '更新时间';
COMMENT ON COLUMN rag_obsidian_configs.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_parse_tasks IS '文档解析任务表: 前端轮询进度';
COMMENT ON COLUMN rag_parse_tasks.task_id IS '任务ID 主键(雪花ID)';
COMMENT ON COLUMN rag_parse_tasks.doc_id IS '文档ID (FK→rag_documents.doc_id)';
COMMENT ON COLUMN rag_parse_tasks.kb_id IS '所属知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_parse_tasks.stage IS '解析阶段: parse解析/chunk分块/embed向量化/extract实体抽取/graph图谱构建/done完成/failed失败';
COMMENT ON COLUMN rag_parse_tasks.status IS '任务状态: running运行中/completed已完成/failed失败';
COMMENT ON COLUMN rag_parse_tasks.progress IS '进度百分比(0-100)';
COMMENT ON COLUMN rag_parse_tasks.error_msg IS '错误信息';
COMMENT ON COLUMN rag_parse_tasks.user_id IS '操作用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_parse_tasks.created_at IS '创建时间';
COMMENT ON COLUMN rag_parse_tasks.updated_at IS '更新时间';
COMMENT ON COLUMN rag_parse_tasks.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_query_logs IS 'RAG检索日志表: 查询统计用';
COMMENT ON COLUMN rag_query_logs.log_id IS '日志ID 主键(雪花ID)';
COMMENT ON COLUMN rag_query_logs.user_id IS '查询用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_query_logs.kb_ids IS '检索的知识库ID列表JSON';
COMMENT ON COLUMN rag_query_logs.query IS '查询文本';
COMMENT ON COLUMN rag_query_logs.mode IS '检索模式: hybrid混合/local局部/global全局';
COMMENT ON COLUMN rag_query_logs.answer_excerpt IS '答案摘要';
COMMENT ON COLUMN rag_query_logs.hit_count IS '命中数量';
COMMENT ON COLUMN rag_query_logs.latency_ms IS '耗时(毫秒)';
COMMENT ON COLUMN rag_query_logs.agent_id IS '使用智能体ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_query_logs.skill_id IS '使用技能ID';
COMMENT ON COLUMN rag_query_logs.sources IS '检索结果来源JSON数组';
COMMENT ON COLUMN rag_query_logs.created_at IS '创建时间';
COMMENT ON COLUMN rag_query_logs.updated_at IS '更新时间';
COMMENT ON COLUMN rag_query_logs.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_doc_permissions IS '文档级权限表: 对单篇文档的显式授权(read/write/admin)';
COMMENT ON COLUMN rag_doc_permissions.id IS '主键ID(雪花ID)';
COMMENT ON COLUMN rag_doc_permissions.doc_id IS '文档ID (FK→rag_documents.doc_id)';
COMMENT ON COLUMN rag_doc_permissions.user_id IS '被授权用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_doc_permissions.perm IS '权限级别: read只读/write可写/admin管理';
COMMENT ON COLUMN rag_doc_permissions.created_at IS '创建时间';
COMMENT ON COLUMN rag_doc_permissions.updated_at IS '更新时间';
COMMENT ON COLUMN rag_doc_permissions.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_relations IS '知识图谱关系表: 实体间关系(图谱边)';
COMMENT ON COLUMN rag_relations.relation_id IS '关系ID 主键(雪花ID)';
COMMENT ON COLUMN rag_relations.kb_id IS '所属知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_relations.doc_id IS '来源文档ID (FK→rag_documents.doc_id)';
COMMENT ON COLUMN rag_relations.src_entity_id IS '源实体ID (FK→rag_entities.entity_id)';
COMMENT ON COLUMN rag_relations.tgt_entity_id IS '目标实体ID (FK→rag_entities.entity_id)';
COMMENT ON COLUMN rag_relations.relation_type IS '关系类型(默认RELATED)';
COMMENT ON COLUMN rag_relations.description IS '关系描述';
COMMENT ON COLUMN rag_relations.keywords IS '关系关键词';
COMMENT ON COLUMN rag_relations.neo4j_edge_id IS 'Neo4j边ID';
COMMENT ON COLUMN rag_relations.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_relations.created_at IS '创建时间';
COMMENT ON COLUMN rag_relations.updated_at IS '更新时间';
COMMENT ON COLUMN rag_relations.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE rag_sync_events IS '同步事件台账表: 记录向Milvus/Neo4j同步的事件, 失败可据此重试';
COMMENT ON COLUMN rag_sync_events.event_id IS '事件ID 主键(雪花ID)';
COMMENT ON COLUMN rag_sync_events.action IS '操作类型: insert新增';
COMMENT ON COLUMN rag_sync_events.target_type IS '目标类型: chunk分块/entity实体/relation关系/resource多模态资源';
COMMENT ON COLUMN rag_sync_events.target_id IS '目标对象ID';
COMMENT ON COLUMN rag_sync_events.doc_id IS '关联文档ID (FK→rag_documents.doc_id)';
COMMENT ON COLUMN rag_sync_events.kb_id IS '所属知识库ID (FK→rag_knowledge_bases.kb_id)';
COMMENT ON COLUMN rag_sync_events.payload IS '同步数据载荷JSON';
COMMENT ON COLUMN rag_sync_events.status IS '同步状态: pending待同步/completed已完成/failed失败';
COMMENT ON COLUMN rag_sync_events.retry_count IS '重试次数';
COMMENT ON COLUMN rag_sync_events.error_msg IS '错误信息';
COMMENT ON COLUMN rag_sync_events.user_id IS '操作用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN rag_sync_events.created_at IS '创建时间';
COMMENT ON COLUMN rag_sync_events.updated_at IS '更新时间';
COMMENT ON COLUMN rag_sync_events.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE sys_users IS '系统用户表: rag/mcp/pro-cowork三系统共享登录用户';
COMMENT ON COLUMN sys_users.user_id IS '用户ID 主键(雪花ID)';
COMMENT ON COLUMN sys_users.name IS '登录名(唯一)';
COMMENT ON COLUMN sys_users.password_hash IS '密码哈希';
COMMENT ON COLUMN sys_users.display_name IS '显示姓名';
COMMENT ON COLUMN sys_users.department IS '所属部门';
COMMENT ON COLUMN sys_users.is_active IS '是否启用';
COMMENT ON COLUMN sys_users.created_at IS '创建时间';
COMMENT ON COLUMN sys_users.updated_at IS '更新时间';
COMMENT ON COLUMN sys_users.is_delete IS '是否软删除: False正常/True已删除';

-- ===============================================================
-- mcp-cowork 表 (MCP 接口维护/测试/统计平台, 含 IM 通道 mcp_im_channels 与巡检报告 mcp_inspect_reports)
-- ===============================================================

COMMENT ON TABLE mcp_call_logs IS 'MCP调用日志表: 全量调用记录(统计页聚合依据)';
COMMENT ON COLUMN mcp_call_logs.log_id IS '日志ID 主键(雪花ID)';
COMMENT ON COLUMN mcp_call_logs.server_id IS '所属服务ID (FK→mcp_servers.server_id)';
COMMENT ON COLUMN mcp_call_logs.tool_name IS '工具名称';
COMMENT ON COLUMN mcp_call_logs.params IS '调用参数JSON';
COMMENT ON COLUMN mcp_call_logs.result_excerpt IS '结果摘要';
COMMENT ON COLUMN mcp_call_logs.latency_ms IS '耗时(毫秒)';
COMMENT ON COLUMN mcp_call_logs.status IS '调用状态: success成功/error失败';
COMMENT ON COLUMN mcp_call_logs.user_id IS '调用用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN mcp_call_logs.created_at IS '创建时间';
COMMENT ON COLUMN mcp_call_logs.updated_at IS '更新时间';
COMMENT ON COLUMN mcp_call_logs.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE mcp_im_channels IS '个人IM通道配置表: 飞书/企微/钉钉/邮箱/OA/Obsidian,每人可配多条';
COMMENT ON COLUMN mcp_im_channels.channel_id IS '通道ID 主键(雪花ID)';
COMMENT ON COLUMN mcp_im_channels.user_id IS '所属用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN mcp_im_channels.channel_type IS '通道类型: feishu飞书/wecom企微/dingtalk钉钉/email邮箱/oa办公/obsidian笔记';
COMMENT ON COLUMN mcp_im_channels.name IS '通道名称(如: 我的飞书群机器人)';
COMMENT ON COLUMN mcp_im_channels.config IS '通道配置JSON(webhook/smtp/api_key等)';
COMMENT ON COLUMN mcp_im_channels.enabled IS '是否启用';
COMMENT ON COLUMN mcp_im_channels.last_test_at IS '最近测试时间';
COMMENT ON COLUMN mcp_im_channels.last_test_status IS '最近测试状态: success成功/error失败';
COMMENT ON COLUMN mcp_im_channels.last_test_error IS '最近测试错误信息';
COMMENT ON COLUMN mcp_im_channels.created_at IS '创建时间';
COMMENT ON COLUMN mcp_im_channels.updated_at IS '更新时间';
COMMENT ON COLUMN mcp_im_channels.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE mcp_inspect_reports IS '工具巡检报告表: 服务健康+工具变更diff+测试用例回归结果';
COMMENT ON COLUMN mcp_inspect_reports.report_id IS '报告ID 主键(雪花ID)';
COMMENT ON COLUMN mcp_inspect_reports.user_id IS '所属用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN mcp_inspect_reports.trigger_type IS '触发方式: manual手动/scheduled定时';
COMMENT ON COLUMN mcp_inspect_reports.verdict IS '巡检结论: pass通过/warn有变更/fail回归失败或服务离线';
COMMENT ON COLUMN mcp_inspect_reports.summary IS '统计摘要JSON(服务/工具变更/用例计数)';
COMMENT ON COLUMN mcp_inspect_reports.detail IS '巡检明细JSON(每服务diff+每用例结果)';
COMMENT ON COLUMN mcp_inspect_reports.created_at IS '创建时间';
COMMENT ON COLUMN mcp_inspect_reports.updated_at IS '更新时间';
COMMENT ON COLUMN mcp_inspect_reports.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE mcp_servers IS 'MCP服务注册表';
COMMENT ON COLUMN mcp_servers.server_id IS '服务ID 主键(雪花ID)';
COMMENT ON COLUMN mcp_servers.name IS '服务名称';
COMMENT ON COLUMN mcp_servers.base_url IS '服务地址URL';
COMMENT ON COLUMN mcp_servers.transport IS '传输协议: streamable_http等';
COMMENT ON COLUMN mcp_servers.description IS '服务描述';
COMMENT ON COLUMN mcp_servers.status IS '服务状态: unknown未知/online在线/offline离线';
COMMENT ON COLUMN mcp_servers.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN mcp_servers.created_at IS '创建时间';
COMMENT ON COLUMN mcp_servers.updated_at IS '更新时间';
COMMENT ON COLUMN mcp_servers.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE mcp_test_cases IS 'MCP测试用例表: 在线测试台保存的用例';
COMMENT ON COLUMN mcp_test_cases.case_id IS '用例ID 主键(雪花ID)';
COMMENT ON COLUMN mcp_test_cases.server_id IS '所属服务ID (FK→mcp_servers.server_id)';
COMMENT ON COLUMN mcp_test_cases.tool_name IS '工具名称';
COMMENT ON COLUMN mcp_test_cases.case_name IS '用例名称';
COMMENT ON COLUMN mcp_test_cases.params IS '调用参数JSON';
COMMENT ON COLUMN mcp_test_cases.last_result IS '最近一次调用结果JSON';
COMMENT ON COLUMN mcp_test_cases.last_status IS '最近一次调用状态: success成功/error失败';
COMMENT ON COLUMN mcp_test_cases.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN mcp_test_cases.created_at IS '创建时间';
COMMENT ON COLUMN mcp_test_cases.updated_at IS '更新时间';
COMMENT ON COLUMN mcp_test_cases.is_delete IS '是否软删除: False正常/True已删除';
COMMENT ON TABLE mcp_tools IS 'MCP工具表: tools/list同步快照';
COMMENT ON COLUMN mcp_tools.tool_id IS '工具ID 主键(雪花ID)';
COMMENT ON COLUMN mcp_tools.server_id IS '所属服务ID (FK→mcp_servers.server_id)';
COMMENT ON COLUMN mcp_tools.tool_name IS '工具名称';
COMMENT ON COLUMN mcp_tools.name_zh IS '工具中文名(同步时从描述首行提取,可手工改)';
COMMENT ON COLUMN mcp_tools.description IS '工具描述';
COMMENT ON COLUMN mcp_tools.input_schema IS '输入参数JSON Schema';
COMMENT ON COLUMN mcp_tools.synced_at IS '最近同步时间';
COMMENT ON COLUMN mcp_tools.user_id IS '创建者用户ID (FK→sys_users.user_id)';
COMMENT ON COLUMN mcp_tools.created_at IS '创建时间';
COMMENT ON COLUMN mcp_tools.updated_at IS '更新时间';
COMMENT ON COLUMN mcp_tools.is_delete IS '是否软删除: False正常/True已删除';
